app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
/*
Route::group(array('prefix' => 'admin'), function()
{
	Route::get('login', array('as' => 'admin.login', 'uses' => 'AdminAuthController@getLogin'));
	Route::post('post', array('as' => 'admin.login.post', 'uses' => 'AdminAuthController@postLogin'));
	Route::get('logout', array('as' => 'admin.logout', 'uses' => 'AdminAuthController@getLogout'));
});	
*/
Route::get('admin.categories.index', [
'before' => "logged:/custom_url",
'uses' => function(){
     echo '123'; die();
}]);
Route::group(array('prefix' => 'admin', /*[
										'before' => 'has_perm:_permissionA,_permissionB',    									
        								'uses' => 'Jacopo\Authentication\Controllers\UserController@getList']*/
					), function(){

							Route::resource('categories', 'AdminCategoriesController',array('only' => array('index','edit','update')));	
							Route::resource('products', 'AdminProductsController',array('only' => array('index','edit','create','store','destroy')));	
							Route::post('products/update/{products}',array('as' => 'admin.products.update', 'uses' => 'AdminProductsController@update'));	

							Route::resource('orders','AdminOrdersController');
							
							Route::resource('pof','AdminProductsOfOrdersController', array('except' => array('create')));

							Route::get('admin/pof/{orderId}/create',array('as' => 'admin.pof.create','uses' => 'AdminProductsOfOrdersController@create',array('only' => array('create'))));

							Route::resource('pages', 'AdminPagesController');

							Route::resource('clients', 'AdminClientsController');

							Route::resource('promos','AdminPromosController');

							Route::resource('settings','AdminSettingsController');
							
							//порядок продуктов
							Route::post('products/order-update',array('as' => 'ord-update', 'uses' => 'AdminCategoriesController@changeOrderOfProduct'));	
							//тестовый
							/*
							Route::get('mail',function(){
								Mail::send('admin.email.hello',array('name' => 'test'), function($message){
									$message->to('ma@helloworld.by', 'Test')->subject('Hello, Are you heare me?');
									echo 123;
								});
							});
							*/
		  
		});


//Route::resource('categories', 'AdminCategoriesController',array('only' => array('index','edit','update')));	


Route::resource('/','BaseController');
//add prod to session
Route::post('add-product',array('as' => 'add.pdoduct', 'uses' => 'BaseController@addProdToCart'));
Route::post('show-cart',array('as' => 'show.cart', 'uses' => 'BaseController@showCart'));
Route::post('del-from-cart',array('as' => 'del.from.cart', 'uses' => 'BaseController@delFromCart'));
Route::post('save-order',array('as' => 'save.order', 'uses' => 'BaseController@saveOrder'));
Route::post('check-promo',array('as' => 'check.promo', 'uses' => 'BaseController@checkPromo'));
Route::post('check-address',array('as' => 'check.address', 'uses' => 'BaseController@checkAddress'));
//страница оплаты заказа
Route::get('payment/{hash}',array('as' => 'order.payment', 'uses' => 'BaseController@payment'));	
//страница удачной или не удачной оплаты
Route::post('payment',array('as' => 'order.payment.result', 'uses' => 'BaseController@paymentResult'));	
//приход платежа
Route::post('payment_came',array('as' => 'order.payment.came', 'uses' => 'BaseController@paymentCame'));
//статические страницы
Route::get('{name}',array('as' => 'static.page', 'uses' => 'BaseController@staticPage'))
->where('name', '[A-Za-z]+');

app/models/Client.php
<?php

class Client extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		// 'title' => 'required'
	];

	// Don't forget to fill this array
	protected $fillable = ['name','phone','address','email'];

	public function orders()
	{
		return $this->hasMany('Order');
	}
}

app/views/admin/clients/create.blade.php
D:\NewXampp\htdocs\vitamin\app/views/clients/create.blade.php

app/views/admin/clients/edit.blade.php
@extends('admin._layouts.admin')
@section('content')
{{ link_to_route('admin.clients.index','Назад')}}
	{{ Form::model($client, array('route' => array('admin.clients.update',$client->id),'method' => 'put'))}}
		@include('admin.clients._partials.form')
	{{ Form::close()}}
	@if($client->orders)
		<h1>Список заказов</h1>
		<ul>
		@foreach($client->orders as $order)
			<li>
				{{link_to_route('admin.orders.show','№ '.$order->id,array($order->id))}}
			</li>
		@endforeach
		</ul>
	@endif
@stop 

app/views/admin/clients/index.blade.php
@extends('admin._layouts.admin')

@section('content')
{{ link_to_route('admin.orders.create','Добавить клмента (создать заказ)')}}
<h1>Клиенты</h1>
{{ Form::open(array('route' => array('admin.clients.index'),'method' => 'get'))}}
	<input name="find">
	{{ Form::submit('Найти') }}			
{{ Form::close()}}
@if(count($clients))
<table class="table table-order table-hover">
    <colgroup>   
                            
        <col width="25%">   
        <col width="15%">   
        <col width="15%">
        <col width="15%">  
        <col width="30%">
        <col width="30%">
    </colgroup>
    <thead>    
	<tr>   		
     	<td>
 		@if($sortingBy =='clients.name')
 			@if($sortingAs=='asc')
 				{{link_to_route('admin.clients.index','ФИО &#9650;',array('sortingBy'=>'clients.name', 'sortingAs'=>'desc'))}}
 			@else
 				{{link_to_route('admin.clients.index','ФИО &#9660;',array('sortingBy'=>'clients.name', 'sortingAs'=>'asc'))}}
 			@endif
 		@else
 			{{link_to_route('admin.clients.index','ФИО',array('sortingBy'=>'clients.name', 'sortingAs'=>'asc'))}}
 		@endif
     	</td>
        <td>
    	@if($sortingBy =='clients.created_at')
 			@if($sortingAs=='asc')
 				{{link_to_route('admin.clients.index','Создан &#9650;',array('sortingBy'=>'clients.created_at', 'sortingAs'=>'desc'))}}
 			@else
 				{{link_to_route('admin.clients.index','Создан &#9660;',array('sortingBy'=>'clients.created_at', 'sortingAs'=>'asc'))}}
 			@endif
 		@else
 			{{link_to_route('admin.clients.index','Создан',array('sortingBy'=>'clients.created_at', 'sortingAs'=>'asc'))}}
 		@endif
        </td>
       	<td>
       	@if($sortingBy =='COUNT(`orders`.`id`)')
 			@if($sortingAs=='asc')
 				{{link_to_route('admin.clients.index','Заказы &#9650;',array('sortingBy'=>'COUNT(`orders`.`id`)', 'sortingAs'=>'desc'))}}
 			@else
 				{{link_to_route('admin.clients.index','Заказы &#9660;',array('sortingBy'=>'COUNT(`orders`.`id`)', 'sortingAs'=>'asc'))}}
 			@endif
 		@else
 			{{link_to_route('admin.clients.index','Заказы',array('sortingBy'=>'COUNT(`orders`.`id`)', 'sortingAs'=>'asc'))}}
 		@endif
       	</td>
        <td>
        @if($sortingBy =='SUM(`orders`.`price`)')
 			@if($sortingAs=='asc')
 				{{link_to_route('admin.clients.index','Сумма &#9650;',array('sortingBy'=>'SUM(`orders`.`price`)', 'sortingAs'=>'desc'))}}
 			@else
 				{{link_to_route('admin.clients.index','Сумма &#9660;',array('sortingBy'=>'SUM(`orders`.`price`)', 'sortingAs'=>'asc'))}}
 			@endif
 		@else
 			{{link_to_route('admin.clients.index','Сумма',array('sortingBy'=>'SUM(`orders`.`price`)', 'sortingAs'=>'asc'))}}
 		@endif	
        </td> 
        <td>
        </td>
        <td>
        </td>
	</tr>
	</thead>
	<tbody>
	@foreach($clients as $client)	
		<tr>			
			<td>{{ link_to_route('admin.clients.edit', $client->name, array($client->id))}}</td>
			<td>{{date('Y-m-d', strtotime($client->created_at))}}</td>
			<td>{{count($client->orders)}}</td>
			<td>{{$client['SUM(`orders`.`price`)']}}</td>		
			<td>{{$client->phone}}</td>
			<td>{{$client->email}}</td>			
		</tr>
	@endforeach
	</tbody>
</table>
@else
<p>Список пуст</p>
@endif
@stop 

app/views/admin/clients/show.blade.php
D:\NewXampp\htdocs\vitamin\app/views/clients/show.blade.php