app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
/*
Route::group(array('prefix' => 'admin'), function()
{
	Route::get('login', array('as' => 'admin.login', 'uses' => 'AdminAuthController@getLogin'));
	Route::post('post', array('as' => 'admin.login.post', 'uses' => 'AdminAuthController@postLogin'));
	Route::get('logout', array('as' => 'admin.logout', 'uses' => 'AdminAuthController@getLogout'));
});	
*/
Route::get('admin.categories.index', [
'before' => "logged:/custom_url",
'uses' => function(){
     echo '123'; die();
}]);
Route::group(array('prefix' => 'admin', /*[
										'before' => 'has_perm:_permissionA,_permissionB',    									
        								'uses' => 'Jacopo\Authentication\Controllers\UserController@getList']*/
					), function(){

							Route::resource('categories', 'AdminCategoriesController',array('only' => array('index','edit','update')));	
							Route::resource('products', 'AdminProductsController',array('only' => array('index','edit','create','store','destroy')));	
							Route::post('products/update/{products}',array('as' => 'admin.products.update', 'uses' => 'AdminProductsController@update'));	

							Route::resource('orders','AdminOrdersController');
							
							Route::resource('pof','AdminProductsOfOrdersController', array('except' => array('create')));

							Route::get('admin/pof/{orderId}/create',array('as' => 'admin.pof.create','uses' => 'AdminProductsOfOrdersController@create',array('only' => array('create'))));

							Route::resource('pages', 'AdminPagesController');

							Route::resource('clients', 'AdminClientsController');

							Route::resource('promos','AdminPromosController');

							Route::resource('settings','AdminSettingsController');
							
							//порядок продуктов
							Route::post('products/order-update',array('as' => 'ord-update', 'uses' => 'AdminCategoriesController@changeOrderOfProduct'));	
							//тестовый
							/*
							Route::get('mail',function(){
								Mail::send('admin.email.hello',array('name' => 'test'), function($message){
									$message->to('ma@helloworld.by', 'Test')->subject('Hello, Are you heare me?');
									echo 123;
								});
							});
							*/
		  
		});


//Route::resource('categories', 'AdminCategoriesController',array('only' => array('index','edit','update')));	


Route::resource('/','BaseController');
//add prod to session
Route::post('add-product',array('as' => 'add.pdoduct', 'uses' => 'BaseController@addProdToCart'));
Route::post('show-cart',array('as' => 'show.cart', 'uses' => 'BaseController@showCart'));
Route::post('del-from-cart',array('as' => 'del.from.cart', 'uses' => 'BaseController@delFromCart'));
Route::post('save-order',array('as' => 'save.order', 'uses' => 'BaseController@saveOrder'));
Route::post('check-promo',array('as' => 'check.promo', 'uses' => 'BaseController@checkPromo'));
Route::post('check-address',array('as' => 'check.address', 'uses' => 'BaseController@checkAddress'));
//страница оплаты заказа
Route::get('payment/{hash}',array('as' => 'order.payment', 'uses' => 'BaseController@payment'));	
//страница удачной или не удачной оплаты
Route::post('payment',array('as' => 'order.payment.result', 'uses' => 'BaseController@paymentResult'));	
//приход платежа
Route::post('payment_came',array('as' => 'order.payment.came', 'uses' => 'BaseController@paymentCame'));
//статические страницы
Route::get('{name}',array('as' => 'static.page', 'uses' => 'BaseController@staticPage'))
->where('name', '[A-Za-z]+');

app/models/Order.php
<?php

class Order extends \Eloquent {

	// Add your validation rules here
	public static $rules = [
		'name' => 'required'
	];

	// Don't forget to fill this array
	protected $fillable = ['name','phone','paid','address','price','orderStatus_id','status','client_id','hash','description'];

	public function products()
	{
		return $this->belongsToMany('Product');
	}

	public function status()
	{
		return $this->belongsTo('OrderStatus','orderStatus_id');
	}

	public function client()
	{
		return $this->belongsTo('Client','client_id');
	}
}

app/views/admin/orders/create.blade.php
@extends('admin._layouts.admin')

@section('content')
	{{ link_to_route('admin.orders.index','Назад')}}
	{{ Form::open(array('route' => array('admin.orders.store')))}}
		@include('admin.orders._partials.form')
	{{ Form::close()}}
@stop

app/views/admin/orders/edit.blade.php
@extends('admin._layouts.admin')
@section('content')
{{ link_to_route('admin.orders.show','Назад',array($order->id))}}
	{{ Form::model($order, array('route' => array('admin.orders.update',$order->id),'method' => 'put'))}}
		@include('admin.orders._partials.form')
	{{ Form::close()}}
@stop 

app/views/admin/orders/index.blade.php
@extends('admin._layouts.admin')

@section('content')
{{ link_to_route('admin.orders.create','Добавить заказ')}}
{{ Form::open(array('route' => array('admin.orders.index'),'method' => 'get'))}}
	<input name="find" @if($find) value="{{$find}}" @endif>
	{{ Form::submit('Найти') }}			
{{ Form::close()}}
{{ Form::open(array('route' => array('admin.orders.index'),'method' => 'get'))}}
	C: <input name="fromDate" type="date" value="{{$fromDate}}">По: <input name="underDate" type="date" value="{{$underDate}}"> 
		<select name="status">
			<option value="0">Все</option>
			@foreach(OrderStatus::lists('name','id') as $key => $val)
				<option @if($status == $key)selected @endif value="{{$key}}">{{$val}}</option>
			@endforeach
		</select>
	{{ Form::submit('Найти') }}			
{{ Form::close()}}
<h1>Заказы</h1>

@if(count($orders))
	<ul>
	@foreach($orders as $order)
		<li>			
			{{ link_to_route('admin.orders.show', $order->name, array($order->id))}}
			{{ Form::open(array('route' => array('admin.orders.destroy',$order->id),'method' => 'delete', 'class' => 'destroy'))}}
			{{ Form::submit('Удалить')}}
			{{ Form::close()}}			
		</li>
	@endforeach
	</ul>
@else
<p>Нет заказов</p>
@endif

@stop 

app/views/admin/orders/show.blade.php
@extends('admin._layouts.admin')

@section('content')
{{ link_to_route('admin.orders.index','Назад') }}
<h1>{{link_to_route('admin.orders.edit','Редактировать заказ',array($order->id))}}</h1>
<p>Статус: {{$order->status->name}}</p>
@if(count($order->client_id))
	<p>{{link_to_route('admin.clients.edit', $order->name, array($order->client_id))}}</p>
@else
	<p>ФИО: {{$order->name}}</p>
@endif
<p>Тел: {{$order->phone}}</p>
<p>адрес: {{$order->address}}</p>
<p>Стоимость: {{$order->price}}</p>
<ul>
@foreach($productsOfOrder as $product)
	<li>
		{{ link_to_route('admin.pof.edit',$product->product->name, array($product->id))}} {{{$product->count}}} кг 
		{{ Form::open(array('route' => array('admin.pof.destroy',$product->id), 'method' => 'delete', 'class' => 'destroy'))}}
		{{ Form::submit('Удалить')}}
		{{ Form::close()}}
	</li>
@endforeach
</ul>
{{ link_to_route('admin.pof.create','Добавить продукт',array($order->id))}}
@stop 